#Interpolation - NEAREST NEIGHBOR
#Per Hour - Outlier 1% DBSCAN (e=0.3-0.8) IF (c=0-0.04)
hour_data_O1 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Hour/O1-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(hour_data_O1$timestamp,hour_data_O1$Test_2)
hour_data_O1$num <- seq_len(length(hour_data_O1$timestamp))
result_hour_O1 <- loess.smooth(hour_data_O1$num, hour_data_O1$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = hour_data_O1$num[length(hour_data_O1$num)] - hour_data_O1$num[1] + 1)
plot(hour_data_O1$num,hour_data_O1$Test_2,type="l",col="red")
lines(result_hour_O1$x,result_hour_O1$y, col="blue", type='p')
hour_data_O1$recovery <- result_hour_O1$y
write.csv(hour_data_O1, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Hour/out-Test_2-O1.csv", row.names = FALSE)
#Per Hour - Outlier 5% DBSCAN (e=0.3) IF SVM
hour_data_O5 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Hour/O5-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(hour_data_O5$timestamp,hour_data_O5$Test_2)
hour_data_O5$num <- seq_len(length(hour_data_O5$timestamp))
result_hour_O5 <- loess.smooth(hour_data_O5$num, hour_data_O5$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = hour_data_O5$num[length(hour_data_O5$num)] - hour_data_O5$num[1] + 1)
plot(hour_data_O5$num,hour_data_O5$Test_2,type="l",col="red")
lines(result_hour_O5$x,result_hour_O5$y, col="blue", type='p')
hour_data_O5$recovery <- result_hour_O5$y
write.csv(hour_data_O5, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Hour/out-Test_2-O5.csv", row.names = FALSE)
#Per Hour - Outlier 10% DBSCAN (e=0.2) IF
hour_data_O10 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Hour/O10-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(hour_data_O10$timestamp,hour_data_O10$Test_2)
hour_data_O10$num <- seq_len(length(hour_data_O10$timestamp))
result_hour_O10 <- loess.smooth(hour_data_O10$num, hour_data_O10$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = hour_data_O10$num[length(hour_data_O10$num)] - hour_data_O10$num[1] + 1)
plot(hour_data_O10$num,hour_data_O10$Test_2,type="l",col="red")
lines(result_hour_O10$x,result_hour_O10$y,col="blue", type='p')
hour_data_O10$recovery <- result_hour_O10$y
write.csv(hour_data_O10, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Hour/out-Test_2-O10.csv", row.names = FALSE)#-----------------------------------------------------------------
#Per Day - Outlier 1% DBSCAN (e=0.2)
day_data_O1 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Day/O1-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(day_data_O1$timestamp,day_data_O1$Test_2)
day_data_O1$num <- seq_len(length(day_data_O1$timestamp))
result_day_O1 <- loess.smooth(day_data_O1$num, day_data_O1$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = day_data_O1$num[length(day_data_O1$num)] - day_data_O1$num[1] + 1)
plot(day_data_O1$num,day_data_O1$Test_2,type="l",col="red")
lines(result_day_O1$x,result_day_O1$y,col="blue", type='p')
day_data_O1$recovery <- result_day_O1$y
write.csv(day_data_O1, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Day/out-Test_2-O1.csv", row.names = FALSE)
#Per Day - Outlier 5% IF(0.07)
day_data_O5 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Day/O5-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(day_data_O5$timestamp,day_data_O5$Test_2)
day_data_O5$num <- seq_len(length(day_data_O5$timestamp))
result_day_O5 <- loess.smooth(day_data_O5$num, day_data_O5$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = day_data_O5$num[length(day_data_O5$num)] - day_data_O5$num[1] + 1)
plot(day_data_O5$num,day_data_O5$Test_2,type="l",col="red")
lines(result_day_O5$x,result_day_O5$y,col="blue", type='p')
day_data_O5$recovery <- result_day_O5$y
write.csv(day_data_O5, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Day/out-Test_2-O5.csv", row.names = FALSE)
#Per Day - Outlier 10% DBSCAN(e=0.2)
day_data_O10 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Day/O10-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(day_data_O10$timestamp,day_data_O10$Test_2)
day_data_O10$num <- seq_len(length(day_data_O10$timestamp))
result_day_O10 <- loess.smooth(day_data_O10$num, day_data_O10$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = day_data_O10$num[length(day_data_O10$num)] - day_data_O10$num[1] + 1)
plot(day_data_O10$num,day_data_O10$Test_2,type="l",col="red")
lines(result_day_O10$x,result_day_O10$y,col="blue", type='p')
day_data_O10$recovery <- result_day_O10$y
write.csv(day_data_O10, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Day/out-Test_2-O10.csv", row.names = FALSE)
#----------------------------------------------------------------
#Per Month - Outlier 1% SVM(0.01)
month_data_O1 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Month/O1-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(month_data_O1$timestamp,month_data_O1$Test_2)
month_data_O1$num <- seq_len(length(month_data_O1$timestamp))
result_month_O1 <- loess.smooth(month_data_O1$num, month_data_O1$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = month_data_O1$num[length(month_data_O1$num)] - month_data_O1$num[1] + 1)
plot(month_data_O1$num,month_data_O1$Test_2,type="l",col="red")
lines(result_month_O1$x,result_month_O1$y,col="blue", type='p')
month_data_O1$recovery <- result_month_O1$y
write.csv(month_data_O1, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Month/out-Test_2-O1.csv", row.names = FALSE)
#Per Month - Outlier 5% DBSCAN (e=0.01)
month_data_O5 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Month/O5-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(month_data_O5$timestamp,month_data_O5$Test_2)
month_data_O5$num <- seq_len(length(month_data_O5$timestamp))
result_month_O5 <- loess.smooth(month_data_O5$num, month_data_O5$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = month_data_O5$num[length(month_data_O5$num)] - month_data_O5$num[1] + 1)
plot(month_data_O5$num,month_data_O5$Test_2,type="l",col="red")
lines(result_month_O5$x,result_month_O5$y,col="blue", type='p')
month_data_O5$recovery <- result_month_O5$y
write.csv(month_data_O5, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Month/out-Test_2-O5.csv", row.names = FALSE)
#Per Month - Outlier 10% IF (c=0.1)
month_data_O10 <- read.table("/media/Moon/Thesis/DataCollection/Failure_Recovery/Per_Month/O10-Test_2.csv", header = TRUE, sep=',' , dec='.')
plot(month_data_O10$timestamp,month_data_O10$Test_2)
month_data_O10$num <- seq_len(length(month_data_O10$timestamp))
result_month_O10 <- loess.smooth(month_data_O10$num, month_data_O10$Test_2, span=1/3, degree = 2,family = c("gaussian"), evaluation = month_data_O10$num[length(month_data_O10$num)] - month_data_O10$num[1] + 1)
plot(month_data_O10$num,month_data_O10$Test_2,type="l",col="red")
lines(result_month_O10$x, result_month_O10$y,col="blue", type='p')
month_data_O10$recovery <- result_month_O10$y
write.csv(month_data_O10, file = "/media/Moon/Thesis/DataCollection/Failure_Recovery/Nearest_Neighbor/Per_Month/out-Test_2-O10.csv", row.names = FALSE)

